export const cardData = [
  {
    createTime: "2024-10-16 10:08:28",
    customEntitySpecAddPermission: false,
    customEntitySpecId: "13775",
    customEntitySpecPermission: false,
    customEntitySpecViewPermission: false,
    displayOrder: 246,
    formSpecAddPermission: false,
    formSpecId: 234810,
    formSpecPermission: false,
    formSpecViewPermission: false,
    formType: null,
    groupIdAndWorkspecIds: null,
    hmId: 1847,
    id: 7132420,
    modifiedTime: "2024-10-16 10:08:28",
    moduleId: 1000,
    moduleName: "leaves",
    quickLinkUrl: null,
    startUp: false,
    visible: false,
    workSpecId: 0,
  },
  {
    createTime: "2024-10-16 10:08:28",
    customEntitySpecAddPermission: false,
    customEntitySpecId: "13775",
    customEntitySpecPermission: false,
    customEntitySpecViewPermission: false,
    displayOrder: 246,
    formSpecAddPermission: false,
    formSpecId: 234810,
    formSpecPermission: false,
    formSpecViewPermission: false,
    formType: null,
    groupIdAndWorkspecIds: null,
    hmId: 1847,
    id: 7132420,
    modifiedTime: "2024-10-16 10:08:28",
    moduleId: 1001,
    moduleName: "day planner",
    quickLinkUrl: null,
    startUp: false,
    visible: false,
    workSpecId: 0,
  },
  {
    createTime: "2024-10-16 10:08:28",
    customEntitySpecAddPermission: false,
    customEntitySpecId: "13775",
    customEntitySpecPermission: false,
    customEntitySpecViewPermission: false,
    displayOrder: 246,
    formSpecAddPermission: false,
    formSpecId: 234810,
    formSpecPermission: false,
    formSpecViewPermission: false,
    formType: null,
    groupIdAndWorkspecIds: null,
    hmId: 1847,
    id: 7132420,
    modifiedTime: "2024-10-16 10:08:28",
    moduleId: 36,
    moduleName: "Customer Information",
    quickLinkUrl: null,
    startUp: false,
    visible: false,
    workSpecId: 0,
  },
  {
    createTime: "2024-10-16 10:08:28",
    customEntitySpecAddPermission: false,
    customEntitySpecId: "13775",
    customEntitySpecPermission: false,
    customEntitySpecViewPermission: false,
    displayOrder: 246,
    formSpecAddPermission: false,
    formSpecId: 234810,
    formSpecPermission: false,
    formSpecViewPermission: false,
    formType: null,
    groupIdAndWorkspecIds: null,
    hmId: 1847,
    id: 7132420,
    modifiedTime: "2024-10-16 10:08:28",
    moduleId: 17,
    moduleName: "Simple form",
    quickLinkUrl: null,
    startUp: false,
    visible: false,
    workSpecId: 0,
  },
  {
    createTime: "2024-10-16 10:08:28",
    customEntitySpecAddPermission: false,
    customEntitySpecId: 2,
    customEntitySpecPermission: false,
    customEntitySpecViewPermission: false,
    displayOrder: 434,
    formSpecAddPermission: true,
    formSpecId: 219245,
    formSpecPermission: false,
    formSpecViewPermission: false,
    formType: 5,
    groupIdAndWorkspecIds: null,
    hmId: 1847,
    id: 7132600,
    modifiedTime: "2024-10-16 10:08:28",
    moduleId: 37,
    moduleName: "Daily Maintenance Log",
    quickLinkUrl: null,
    startUp: false,
    visible: false,
    workSpecId: 0,
  },
  {
    createTime: "2024-10-16 10:08:28",
    customEntitySpecAddPermission: false,
    customEntitySpecId: "0",
    customEntitySpecPermission: false,
    customEntitySpecViewPermission: false,
    displayOrder: 7,
    formSpecAddPermission: false,
    formSpecId: 0,
    formSpecPermission: false,
    formSpecViewPermission: false,
    formType: null,
    groupIdAndWorkspecIds: null,
    hmId: 1847,
    id: 7132234,
    modifiedTime: "2024-10-16 10:08:28",
    moduleId: 9,
    moduleName: "Customers",
    quickLinkUrl: null,
    startUp: false,
    visible: true,
    workSpecId: 0,
  },
  {
    createTime: "2024-10-16 10:08:28",
    customEntitySpecAddPermission: false,
    customEntitySpecId: "0",
    customEntitySpecPermission: false,
    customEntitySpecViewPermission: false,
    displayOrder: 11,
    formSpecAddPermission: false,
    formSpecId: 0,
    formSpecPermission: false,
    formSpecViewPermission: false,
    formType: null,
    groupIdAndWorkspecIds: null,
    hmId: 1847,
    id: 7132238,
    modifiedTime: "2024-10-16 10:08:28",
    moduleId: 12,
    moduleName: "Knowledge Base",
    quickLinkUrl: null,
    startUp: false,
    visible: true,
    workSpecId: 0,
  },
  {
    createTime: "2024-10-16 10:08:28",
    customEntitySpecAddPermission: false,
    customEntitySpecId: 1,
    customEntitySpecPermission: false,
    customEntitySpecViewPermission: false,
    displayOrder: 246,
    formSpecAddPermission: false,
    formSpecId: 234810,
    formSpecPermission: false,
    formSpecViewPermission: false,
    formType: null,
    groupIdAndWorkspecIds: null,
    hmId: 1847,
    id: 7132420,
    modifiedTime: "2024-10-16 10:08:28",
    moduleId: 34,
    moduleName: "30-08-203 Staging checklist",
    quickLinkUrl: null,
    startUp: false,
    visible: false,
    workSpecId: 0,
  },
];

export const workSpecsData = [
  {
    customEntitySpecId: 1,
    moduleName: "Work Specification 1",
    formSpecId: 100,
    employeeAccessSettings: { addJob: true },
    tasks: {
      todo: { personal: 0, team: 2 },
      invitations: { personal: 3, team: 0 },
      noProgress: 10,
    },
  },
  {
    customEntitySpecId: 2,
    moduleName: "Work Specification 2",
    formSpecId: 200,
    employeeAccessSettings: { addJob: false },
    tasks: {
      todo: { personal: 1, team: 1 },
      invitations: { personal: 1, team: 2 },
      noProgress: 5,
    },
  },
];


