export const cardData = [

    {
      "createTime": "2024-10-16 10:08:28",
      "customEntitySpecAddPermission": false,
      "customEntitySpecId": "13775",
      "customEntitySpecPermission": false,
      "customEntitySpecViewPermission": false,
      "displayOrder": 246,
      "formSpecAddPermission": false,
      "formSpecId": 234810,
      "formSpecPermission": false,
      "formSpecViewPermission": false,
      "formType": null,
      "groupIdAndWorkspecIds": null,
      "hmId": 1847,
      "id": 7132420,
      "modifiedTime": "2024-10-16 10:08:28",
      "moduleId": 36,
      "moduleName": "30-08-203 Staging checklist",
      "quickLinkUrl": null,
      "startUp": false,
      "visible": false,
      "workSpecId": 0
    
    },

    {
      "createTime": "2024-10-16 10:08:28",
      "customEntitySpecAddPermission": false,
      "customEntitySpecId": "13775",
      "customEntitySpecPermission": false,
      "customEntitySpecViewPermission": false,
      "displayOrder": 246,
      "formSpecAddPermission": false,
      "formSpecId": 234810,
      "formSpecPermission": false,
      "formSpecViewPermission": false,
      "formType": null,
      "groupIdAndWorkspecIds": null,
      "hmId": 1847,
      "id": 7132420,
      "modifiedTime": "2024-10-16 10:08:28",
      "moduleId": 17,
      "moduleName": "30-08-203 Staging checklist",
      "quickLinkUrl": null,
      "startUp": false,
      "visible": false,
      "workSpecId": 0
    
    },

   {
      "createTime": "2024-10-16 10:08:28",
      "customEntitySpecAddPermission": false,
      "customEntitySpecId": "2ac97f5c-a161-4d39-90d0-2ceffa2719f0",
      "customEntitySpecPermission": false,
      "customEntitySpecViewPermission": false,
      "displayOrder": 434,
      "formSpecAddPermission": true,
      "formSpecId": 219245,
      "formSpecPermission": false,
      "formSpecViewPermission": false,
      "formType": 5,
      "groupIdAndWorkspecIds": null,
      "hmId": 1847,
      "id": 7132600,
      "modifiedTime": "2024-10-16 10:08:28",
      "moduleId": 37,
      "moduleName": "Daily Maintenance Log",
      "quickLinkUrl": null,
      "startUp": false,
      "visible": false,
      "workSpecId": 0
    }
,
     {
      "createTime": "2024-10-16 10:08:28",
      "customEntitySpecAddPermission": false,
      "customEntitySpecId": "0",
      "customEntitySpecPermission": false,
      "customEntitySpecViewPermission": false,
      "displayOrder": 7,
      "formSpecAddPermission": false,
      "formSpecId": 0,
      "formSpecPermission": false,
      "formSpecViewPermission": false,
      "formType": null,
      "groupIdAndWorkspecIds": null,
      "hmId": 1847,
      "id": 7132234,
      "modifiedTime": "2024-10-16 10:08:28",
      "moduleId": 9,
      "moduleName": "Customers",
      "quickLinkUrl": null,
      "startUp": false,
      "visible": true,
      "workSpecId": 0
    }    
,
    {
      "createTime": "2024-10-16 10:08:28",
      "customEntitySpecAddPermission": false,
      "customEntitySpecId": "0",
      "customEntitySpecPermission": false,
      "customEntitySpecViewPermission": false,
      "displayOrder": 11,
      "formSpecAddPermission": false,
      "formSpecId": 0,
      "formSpecPermission": false,
      "formSpecViewPermission": false,
      "formType": null,
      "groupIdAndWorkspecIds": null,
      "hmId": 1847,
      "id": 7132238,
      "modifiedTime": "2024-10-16 10:08:28",
      "moduleId": 12,
      "moduleName": "Knowledge Base",
      "quickLinkUrl": null,
      "startUp": false,
      "visible": true,
      "workSpecId": 0
    },

    {
      "createTime": "2024-10-16 10:08:28",
      "customEntitySpecAddPermission": false,
      "customEntitySpecId": "13775",
      "customEntitySpecPermission": false,
      "customEntitySpecViewPermission": false,
      "displayOrder": 246,
      "formSpecAddPermission": false,
      "formSpecId": 234810,
      "formSpecPermission": false,
      "formSpecViewPermission": false,
      "formType": null,
      "groupIdAndWorkspecIds": null,
      "hmId": 1847,
      "id": 7132420,
      "modifiedTime": "2024-10-16 10:08:28",
      "moduleId": 34,
      "moduleName": "30-08-203 Staging checklist",
      "quickLinkUrl": null,
      "startUp": false,
      "visible": false,
      "workSpecId": 0
    
    },
  
    
];
