export const DayPlannerModuleMenu =({
  plannedCount,
  actualCount,
  unplannedCount,
  teamPlannedCount,
  teamUnplannedCount,
}) => [
    {id:1,
      count: plannedCount,
      title: "Planned Today",
    },
    {id:2,
      count: actualCount, 
      title: "Visited ",
    },
    {
      id:3,
      count: unplannedCount, 
      title: "unplanned visits",
    },
    {id:4,
      count: teamPlannedCount, 
      title: "team planned employees",
    },
    {id:5,
      count: teamUnplannedCount, 
      title: " team unplanned employees",
    },
   
  ];