export const CustomerData = [
  {
    apiUserId: null,
    brNo: null,
    c1001: null,
    categoryDisplayValue: null,
    categoryFieldValue: null,
    checkinLocationTime: null,
    checksum: null,
    clientCustomerFormId: null,
    clientCustomerId: null,
    clientSideId: null,
    companyId: 8106,
    count: null,
    createdTimeChecked: false,
    createTime: "2024-09-16 10:42:17",
    currentOADisplayValue: null,
    currentOAFieldValue: null,
    customerAccessSettings: null,
    customerAdditionalContactInformation: null,

    customerAddressarea: null,
    customerAddresscity: null,
    customerAddresscountry: null,
    customerAddressdistrict: null,
    customerAddresslandmark: null,
    customerAddresspincode: null,
    customerAddressstate: null,
    customerAddressstreet: null,

    customerCheckin: false,
    customerCheckinCheckOut: false,
    customerCheckinId: null,
    customerCreatedBy: null,
    customerCreatedByName: null,
    customerEmailVerification: 0,
    customerEvents: null,
    customerFormId: 4444400000003134177,
    customerGraphFilter: false,
    customerHierarchy: null,
    customerId: 637,
    customerIds: null,
    customerLat: null,
    customerLong: null,
    customerModifiedBy: null,
    customerName: "001 new 1",
    customerNo: null,
    customerNoForDelete: null,
    customerPhone: 8767892161,
    customerSearchName: null,
    customersMapped: null,
    customerTerritoryId: null,
    customerType: null,
    customerTypeColorName: null,
    customerTypeId: 0,
    customerTypeName: null,
    customerTypes: null,
    customerVisitCompleted: false,
    customTagsCSV: null,
    dayList: null,
    dayPlanDate: null,
    deleted: false,
    empFirstName: null,
    empIdForMappedCustomers: null,
    empLastName: null,
    employeeId: null,
    empName: null,
    enableAddJobInMap: true,
    entities: null,
    entitySpecs: null,
    error: null,
    eventEntities: null,
    externalId: null,
    fields: null,
    fieldsListFilteringMap: null,
    filtCustomerIds: null,
    filtCustomersCondition: null,
    filtType: null,
    formAndField: null,
    fromDateTime: null,
    graphFilterCustomerIds: null,
    htmlTitle: null,
    ignoreCustomerUserDefinedFields: false,
    incompleteCustInDP: false,
    incompleteWorksCount: 0,
    isBulkUpload: false,
    isOpenMap: false,
    isParentString: null,
    isUpdateFromRequisition: false,
    jobLabel: "Job",
    lastCheckedInTime: "1970-01-01 00:00:00",
    locked: false,
    lockedBy: null,
    lockedTime: null,
    logoUrl: null,
    mandatoryActivities: false,
    managerNamesCsvL1: null,
    managerNamesCsvL2: null,
    mandatoryActivityCondition: null,
    mapped: false,
    mappedEmpName: null,
    mapToEmpIds: null,
    mapToEmpNos: null,
    modifiedTime: null,
    modifiedTimeChecked: false,
    monthMap: null,
    nearestCustomers: null,
    nearestCustomers1: null,
    newCustomer: false,
    oaCategoryEntityId: null,
    order: null,
    parent: false,
    parentFormId: null,
    parentId: -1,
    parentName: null,
    parentPropExistsInAPI: false,
    plannedVisitFromDate: null,
    plannedVisitToDate: null,
    presentInRoutes: null,
    primaryContactEmail: null,
    primaryContactFirstName: null,
    primaryContactLastName: null,
    primaryContactPhone: null,
    primaryContactPhotoUrl: null,
    primaryContactTitle: null,
    remarks: null,
    requestDomain: null,
    requisitionFormId: null,

    secondaryContactemail: "New1@gmail.com",
    secondaryContactfirstName: null,
    secondaryContactlastName: null,
    secondaryContactphone: null,
    secondaryContactphotoUrl: null,
    secondaryContacttitle: null,
    sourceOfAction: 2,
    sourceOfModification: null,
    specialTagsCSV: null,
    statusBean: null,
    tagId: null,
    tagIds: null,
    tagName: null,
    territoryIds: null,
    territoryName: null,
    toDateTime: null,
    webUser: false,
    yearList: null,
  },
  {
    apiUserId: null,
    brNo: null,
    c1001: null,
    categoryDisplayValue: null,
    categoryFieldValue: null,
    checkinLocationTime: null,
    checksum: null,
    clientCustomerFormId: null,
    clientCustomerId: null,
    clientSideId: null,
    companyId: 8106,
    count: null,
    createdTimeChecked: false,
    createTime: "2024-09-16 10:42:17",
    currentOADisplayValue: null,
    currentOAFieldValue: null,
    customerAccessSettings: null,
    customerAdditionalContactInformation: null,

    customerAddressarea: null,
    customerAddresscity: null,
    customerAddresscountry: null,
    customerAddressdistrict: null,
    customerAddresslandmark: null,
    customerAddresspincode: null,
    customerAddressstate: null,
    customerAddressstreet: null,

    customerCheckin: false,
    customerCheckinCheckOut: false,
    customerCheckinId: null,
    customerCreatedBy: null,
    customerCreatedByName: null,
    customerEmailVerification: 0,
    customerEvents: null,
    customerFormId: 4444400000003134177,
    customerGraphFilter: false,
    customerHierarchy: null,
    customerId: 630,
    customerIds: null,
    customerLat: null,
    customerLong: null,
    customerModifiedBy: null,
    customerName: "sahana",
    customerNo: null,
    customerNoForDelete: null,
    customerPhone: null,
    customerSearchName: null,
    customersMapped: null,
    customerTerritoryId: null,
    customerType: null,
    customerTypeColorName: null,
    customerTypeId: 0,
    customerTypeName: null,
    customerTypes: null,
    customerVisitCompleted: false,
    customTagsCSV: null,
    dayList: null,
    dayPlanDate: null,
    deleted: false,
    empFirstName: null,
    empIdForMappedCustomers: null,
    empLastName: null,
    employeeId: null,
    empName: null,
    enableAddJobInMap: true,
    entities: null,
    entitySpecs: null,
    error: null,
    eventEntities: null,
    externalId: null,
    fields: null,
    fieldsListFilteringMap: null,
    filtCustomerIds: null,
    filtCustomersCondition: null,
    filtType: null,
    formAndField: null,
    fromDateTime: null,
    graphFilterCustomerIds: null,
    htmlTitle: null,
    ignoreCustomerUserDefinedFields: false,
    incompleteCustInDP: false,
    incompleteWorksCount: 0,
    isBulkUpload: false,
    isOpenMap: false,
    isParentString: null,
    isUpdateFromRequisition: false,
    jobLabel: "Job",
    lastCheckedInTime: "1970-01-01 00:00:00",
    locked: false,
    lockedBy: null,
    lockedTime: null,
    logoUrl: null,
    mandatoryActivities: false,
    managerNamesCsvL1: null,
    managerNamesCsvL2: null,
    mandatoryActivityCondition: null,
    mapped: false,
    mappedEmpName: null,
    mapToEmpIds: null,
    mapToEmpNos: null,
    modifiedTime: null,
    modifiedTimeChecked: false,
    monthMap: null,
    nearestCustomers: null,
    nearestCustomers1: null,
    newCustomer: false,
    oaCategoryEntityId: null,
    order: null,
    parent: false,
    parentFormId: null,
    parentId: -1,
    parentName: null,
    parentPropExistsInAPI: false,
    plannedVisitFromDate: null,
    plannedVisitToDate: null,
    presentInRoutes: null,
    primaryContactEmail: null,
    primaryContactFirstName: null,
    primaryContactLastName: null,
    primaryContactPhone: null,
    primaryContactPhotoUrl: null,
    primaryContactTitle: null,
    remarks: null,
    requestDomain: null,
    requisitionFormId: null,

    secondaryContactemail: "New1@gmail.com",
    secondaryContactfirstName: null,
    secondaryContactlastName: null,
    secondaryContactphone: null,
    secondaryContactphotoUrl: null,
    secondaryContacttitle: null,
    sourceOfAction: 2,
    sourceOfModification: null,
    specialTagsCSV: null,
    statusBean: null,
    tagId: null,
    tagIds: null,
    tagName: null,
    territoryIds: null,
    territoryName: null,
    toDateTime: null,
    webUser: false,
    yearList: null,
  },
  {
    apiUserId: null,
    brNo: null,
    c1001: null,
    categoryDisplayValue: null,
    categoryFieldValue: null,
    checkinLocationTime: null,
    checksum: null,
    clientCustomerFormId: null,
    clientCustomerId: null,
    clientSideId: null,
    companyId: 8106,
    count: null,
    createdTimeChecked: false,
    createTime: "2024-09-16 10:42:17",
    currentOADisplayValue: null,
    currentOAFieldValue: null,
    customerAccessSettings: null,
    customerAdditionalContactInformation: null,

    customerAddressarea: null,
    customerAddresscity: null,
    customerAddresscountry: null,
    customerAddressdistrict: null,
    customerAddresslandmark: null,
    customerAddresspincode: null,
    customerAddressstate: null,
    customerAddressstreet: null,

    customerCheckin: false,
    customerCheckinCheckOut: false,
    customerCheckinId: null,
    customerCreatedBy: null,
    customerCreatedByName: null,
    customerEmailVerification: 0,
    customerEvents: null,
    customerFormId: 4444400000003134177,
    customerGraphFilter: false,
    customerHierarchy: null,
    customerId: 633,
    customerIds: null,
    customerLat: null,
    customerLong: null,
    customerModifiedBy: null,
    customerName: "kishonre",
    customerNo: null,
    customerNoForDelete: null,
    customerPhone: null,
    customerSearchName: null,
    customersMapped: null,
    customerTerritoryId: null,
    customerType: null,
    customerTypeColorName: null,
    customerTypeId: 0,
    customerTypeName: null,
    customerTypes: null,
    customerVisitCompleted: false,
    customTagsCSV: null,
    dayList: null,
    dayPlanDate: null,
    deleted: false,
    empFirstName: null,
    empIdForMappedCustomers: null,
    empLastName: null,
    employeeId: null,
    empName: null,
    enableAddJobInMap: true,
    entities: null,
    entitySpecs: null,
    error: null,
    eventEntities: null,
    externalId: null,
    fields: null,
    fieldsListFilteringMap: null,
    filtCustomerIds: null,
    filtCustomersCondition: null,
    filtType: null,
    formAndField: null,
    fromDateTime: null,
    graphFilterCustomerIds: null,
    htmlTitle: null,
    ignoreCustomerUserDefinedFields: false,
    incompleteCustInDP: false,
    incompleteWorksCount: 0,
    isBulkUpload: false,
    isOpenMap: false,
    isParentString: null,
    isUpdateFromRequisition: false,
    jobLabel: "Job",
    lastCheckedInTime: "1970-01-01 00:00:00",
    locked: false,
    lockedBy: null,
    lockedTime: null,
    logoUrl: null,
    mandatoryActivities: false,
    managerNamesCsvL1: null,
    managerNamesCsvL2: null,
    mandatoryActivityCondition: null,
    mapped: false,
    mappedEmpName: null,
    mapToEmpIds: null,
    mapToEmpNos: null,
    modifiedTime: null,
    modifiedTimeChecked: false,
    monthMap: null,
    nearestCustomers: null,
    nearestCustomers1: null,
    newCustomer: false,
    oaCategoryEntityId: null,
    order: null,
    parent: false,
    parentFormId: null,
    parentId: -1,
    parentName: null,
    parentPropExistsInAPI: false,
    plannedVisitFromDate: null,
    plannedVisitToDate: null,
    presentInRoutes: null,
    primaryContactEmail: null,
    primaryContactFirstName: null,
    primaryContactLastName: null,
    primaryContactPhone: null,
    primaryContactPhotoUrl: null,
    primaryContactTitle: null,
    remarks: null,
    requestDomain: null,
    requisitionFormId: null,

    secondaryContactemail: "New1@gmail.com",
    secondaryContactfirstName: null,
    secondaryContactlastName: null,
    secondaryContactphone: null,
    secondaryContactphotoUrl: null,
    secondaryContacttitle: null,
    sourceOfAction: 2,
    sourceOfModification: null,
    specialTagsCSV: null,
    statusBean: null,
    tagId: null,
    tagIds: null,
    tagName: null,
    territoryIds: null,
    territoryName: null,
    toDateTime: null,
    webUser: false,
    yearList: null,
  },
];
export const CustomerModuleMenu = [
  {id:1,
    count: 5,
    title: "Assigned to you",
  },
  {id:2,
    count: 199, 
    title: "Visited today",
  },
  {
    id:3,
    count: 2, 
    title: "Coverage",
  },
  {id:4,
    count: 1, 
    title: "You haven't visited in the past 30 days",
  },
  {id:5,
    count: 0, 
    title: "Assigned to team",
  },
  {id:6,
    count: 10, 
    title: "Visited by the team yesterday",
  },
  {id:7,
    count: 30, 
    title: "Visited by the team today",
  },
  {id:8,
    count: 0,
    title: "Team hasn't visited in the past 30 days",
  },
];
